[build]
  publish = "."

# Redirecionamento da Recuperação
[[redirects]]
  from = "/auth/recuperar"
  to = "/auth/recuperar.html"
  status = 200

# Redirecionamento da Confirmação
[[redirects]]
  from = "/auth/confirmar"
  to = "/auth/confirmar.html"
  status = 200

# Qualquer outra coisa vai para o Index (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200