[build]
  command = "npx expo export -p web"
  publish = "dist"

# REGRA 1: Permite acessar os arquivos da pasta auth (recuperar senha)
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

# REGRA 2: Todo o resto vai para o App (React Native Web)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200